In [1]:
documents = [
    {
        "doc_id": "POL001",
        "category": "policy",
        "title": "Listing Suppression for Missing Mandatory Attributes",
        "content": "Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation."
    },
    {
        "doc_id": "POL002",
        "category": "policy",
        "title": "Image Compliance Requirements",
        "content": "Product listings may be restricted or hidden if primary images do not meet marketplace quality guidelines. Common violations include watermarks, text overlays, blurred images, incorrect background color, and non-product promotional graphics. Sellers should replace non-compliant images and wait for reprocessing."
    },
    {
        "doc_id": "POL003",
        "category": "policy",
        "title": "Restricted Product Review Process",
        "content": "Some products require compliance review before becoming active. Listings may remain inactive if supporting safety documents, certifications, or approval forms are incomplete. Sellers should check compliance requests, upload required documentation, and monitor review status."
    },
    {
        "doc_id": "OPS001",
        "category": "operations",
        "title": "Inventory Mismatch Troubleshooting",
        "content": "Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantities. Common causes include delayed inventory feeds, unprocessed returns, inbound shipment discrepancies, and stranded units. Sellers should reconcile inventory reports, verify inbound receipts, and review stranded inventory cases."
    },
    {
        "doc_id": "OPS002",
        "category": "operations",
        "title": "Late Shipment Prevention",
        "content": "Late shipment risk increases when order handling time, warehouse processing delays, or carrier pickup issues affect dispatch deadlines. Sellers should confirm handling time settings, monitor cutoff windows, prioritize high-risk orders, and use reliable carriers with valid tracking."
    },
    {
        "doc_id": "OPS003",
        "category": "operations",
        "title": "Stranded Inventory Resolution",
        "content": "Inventory becomes stranded when units in the fulfillment network are not linked to an active buyable listing. Common reasons include closed listings, pricing errors, policy issues, or missing product information. Sellers should relink inventory to active listings, fix listing defects, or create removal orders if needed."
    },
    {
        "doc_id": "ACC001",
        "category": "account_health",
        "title": "Order Defect Rate Warning",
        "content": "Order defect rate reflects negative customer outcomes such as A-to-z claims, chargebacks, and negative feedback. High order defect rate may trigger warnings or account health interventions. Sellers should review recent incidents, address root causes, and submit an appeal with corrective actions if required."
    },
    {
        "doc_id": "ACC002",
        "category": "account_health",
        "title": "Late Shipment Rate Threshold",
        "content": "Late shipment rate measures the percentage of seller-fulfilled orders confirmed after the expected ship date. Sustained late shipment rate breaches may affect account health. Sellers should improve order processing, reduce backlog, and verify shipping confirmation workflows."
    },
    {
        "doc_id": "ACC003",
        "category": "account_health",
        "title": "Valid Tracking Rate Compliance",
        "content": "Valid tracking rate measures how often shipments include usable carrier tracking information. Low tracking validity may lead to account performance issues. Sellers should use supported carriers, ensure correct carrier mapping, and avoid manual tracking entry errors."
    },
    {
        "doc_id": "PAY001",
        "category": "payments",
        "title": "Reimbursement Rejection Due to Missing Documentation",
        "content": "Reimbursement claims may be rejected when invoices, proof of ownership, shipment records, or supporting documentation are incomplete or inconsistent. Sellers should review claim requirements, attach complete evidence, and resubmit within the eligibility window."
    },
    {
        "doc_id": "PAY002",
        "category": "payments",
        "title": "Eligibility Window for Reimbursement Claims",
        "content": "Reimbursement requests must be submitted within the allowed claim window for the issue type. Claims submitted after the allowed period may be automatically denied. Sellers should verify claim timing, issue category, and supporting records before submission."
    },
    {
        "doc_id": "PAY003",
        "category": "payments",
        "title": "Common Causes of Payment Holds",
        "content": "Payment holds may occur due to identity verification issues, unusual account activity, unresolved policy concerns, or missing tax and banking information. Sellers should review account notifications, complete verification tasks, and confirm payout settings."
    }
]

In [3]:
import os
import sys
os.makedirs("srs", exist_ok=True)
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
sys.path.append("/content")
print("Folders created successully")

Folders created successully

In [4]:
!pip install pandas numpy -q

In [5]:
import pandas as pd
import numpy as np
print("Libraries imported successfully")

Libraries imported successfully

In [6]:
documents = [
    {
        "doc_id": "POL001",
        "category": "policy",
        "title": "Listing Suppression for Missing Mandatory Attributes",
        "content": "Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation."
    },
    {
        "doc_id": "POL002",
        "category": "policy",
        "title": "Image Compliance Requirements",
        "content": "Product listings may be restricted or hidden if primary images do not meet marketplace quality guidelines. Common violations include watermarks, text overlays, blurred images, incorrect background color, and non-product promotional graphics. Sellers should replace non-compliant images and wait for reprocessing."
    },
    {
        "doc_id": "POL003",
        "category": "policy",
        "title": "Restricted Product Review Process",
        "content": "Some products require compliance review before becoming active. Listings may remain inactive if supporting safety documents, certifications, or approval forms are incomplete. Sellers should check compliance requests, upload required documentation, and monitor review status."
    },
    {
        "doc_id": "POL004",
        "category": "policy",
        "title": "Title and Description Quality Rules",
        "content": "Listings may lose visibility if titles and descriptions contain promotional claims, keyword stuffing, irrelevant terms, or misleading product information. Sellers should rewrite titles and descriptions using accurate, concise, and product-relevant language."
    },
    {
        "doc_id": "POL005",
        "category": "policy",
        "title": "Duplicate Listing Policy",
        "content": "Multiple listings for the same product may create duplication issues and suppress offer visibility. Sellers should consolidate duplicate listings, verify correct identifiers, and maintain one valid product detail page per unique item."
    },
    {
        "doc_id": "POL006",
        "category": "policy",
        "title": "Hazmat and Safety Documentation Requirements",
        "content": "Products classified as hazardous or safety-sensitive may require additional documentation before listing activation. Missing or invalid hazmat records can block listing availability. Sellers should review safety documentation requests and submit the required forms."
    },
    {
        "doc_id": "OPS001",
        "category": "operations",
        "title": "Inventory Mismatch Troubleshooting",
        "content": "Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantities. Common causes include delayed inventory feeds, unprocessed returns, inbound shipment discrepancies, and stranded units. Sellers should reconcile inventory reports, verify inbound receipts, and review stranded inventory cases."
    },
    {
        "doc_id": "OPS002",
        "category": "operations",
        "title": "Late Shipment Prevention",
        "content": "Late shipment risk increases when order handling time, warehouse processing delays, or carrier pickup issues affect dispatch deadlines. Sellers should confirm handling time settings, monitor cutoff windows, prioritize high-risk orders, and use reliable carriers with valid tracking."
    },
    {
        "doc_id": "OPS003",
        "category": "operations",
        "title": "Stranded Inventory Resolution",
        "content": "Inventory becomes stranded when units in the fulfillment network are not linked to an active buyable listing. Common reasons include closed listings, pricing errors, policy issues, or missing product information. Sellers should relink inventory to active listings, fix listing defects, or create removal orders if needed."
    },
    {
        "doc_id": "OPS004",
        "category": "operations",
        "title": "Inbound Shipment Receiving Delays",
        "content": "Inbound receiving delays may happen when fulfillment centers experience backlog, shipment plan mismatches, labeling errors, or appointment issues. Sellers should review shipment status, confirm carton compliance, and allow additional processing time before escalation."
    },
    {
        "doc_id": "OPS005",
        "category": "operations",
        "title": "Handling High Cancellation Risk Orders",
        "content": "Order cancellations may increase when stock accuracy is poor, lead times are misconfigured, or fulfillment capacity is constrained. Sellers should maintain accurate availability, reduce manual processing delays, and align promise dates with actual capacity."
    },
    {
        "doc_id": "OPS006",
        "category": "operations",
        "title": "Carrier Pickup Failure Response",
        "content": "Carrier pickup failures can lead to missed dispatch deadlines and late shipment rate increases. Sellers should maintain backup carrier arrangements, monitor pickup performance, and escalate recurring pickup failures with logistics partners."
    },
    {
        "doc_id": "ACC001",
        "category": "account_health",
        "title": "Order Defect Rate Warning",
        "content": "Order defect rate reflects negative customer outcomes such as A-to-z claims, chargebacks, and negative feedback. High order defect rate may trigger warnings or account health interventions. Sellers should review recent incidents, address root causes, and submit an appeal with corrective actions if required."
    },
    {
        "doc_id": "ACC002",
        "category": "account_health",
        "title": "Late Shipment Rate Threshold",
        "content": "Late shipment rate measures the percentage of seller-fulfilled orders confirmed after the expected ship date. Sustained late shipment rate breaches may affect account health. Sellers should improve order processing, reduce backlog, and verify shipping confirmation workflows."
    },
    {
        "doc_id": "ACC003",
        "category": "account_health",
        "title": "Valid Tracking Rate Compliance",
        "content": "Valid tracking rate measures how often shipments include usable carrier tracking information. Low tracking validity may lead to account performance issues. Sellers should use supported carriers, ensure correct carrier mapping, and avoid manual tracking entry errors."
    },
    {
        "doc_id": "ACC004",
        "category": "account_health",
        "title": "Appeal Submission Best Practices",
        "content": "Appeals are more effective when they clearly describe the root cause, corrective actions, and preventive actions taken. Sellers should avoid vague explanations and provide measurable process improvements in appeal responses."
    },
    {
        "doc_id": "ACC005",
        "category": "account_health",
        "title": "Customer Complaint Escalation Risk",
        "content": "Repeated complaints related to item condition, inaccurate listings, or late delivery may increase account health risk. Sellers should review complaint patterns, improve listing accuracy, and strengthen fulfillment controls."
    },
    {
        "doc_id": "ACC006",
        "category": "account_health",
        "title": "Performance Notification Review Workflow",
        "content": "Performance notifications may indicate risks related to policy compliance, shipping performance, or customer experience. Sellers should review notification details promptly, identify the affected metric, and complete recommended corrective actions."
    },
    {
        "doc_id": "PAY001",
        "category": "payments",
        "title": "Reimbursement Rejection Due to Missing Documentation",
        "content": "Reimbursement claims may be rejected when invoices, proof of ownership, shipment records, or supporting documentation are incomplete or inconsistent. Sellers should review claim requirements, attach complete evidence, and resubmit within the eligibility window."
    },
    {
        "doc_id": "PAY002",
        "category": "payments",
        "title": "Eligibility Window for Reimbursement Claims",
        "content": "Reimbursement requests must be submitted within the allowed claim window for the issue type. Claims submitted after the allowed period may be automatically denied. Sellers should verify claim timing, issue category, and supporting records before submission."
    },
    {
        "doc_id": "PAY003",
        "category": "payments",
        "title": "Common Causes of Payment Holds",
        "content": "Payment holds may occur due to identity verification issues, unusual account activity, unresolved policy concerns, or missing tax and banking information. Sellers should review account notifications, complete verification tasks, and confirm payout settings."
    },
    {
        "doc_id": "PAY004",
        "category": "payments",
        "title": "Chargeback Dispute Documentation",
        "content": "Chargeback disputes require supporting records such as order details, fulfillment confirmation, delivery evidence, and buyer communication history. Missing dispute evidence may reduce reversal success. Sellers should prepare complete case files before submission."
    },
    {
        "doc_id": "PAY005",
        "category": "payments",
        "title": "Invoice Validation for Reimbursement Cases",
        "content": "Invoices used for reimbursement or investigation support should match product identifiers, quantities, supplier information, and transaction details. Invalid or mismatched invoices may cause case rejection or extended review time."
    },
    {
        "doc_id": "PAY006",
        "category": "payments",
        "title": "Payout Delay Due to Banking Verification",
        "content": "Payout delays may occur when banking details are incomplete, recently changed, or pending verification. Sellers should confirm bank account information, respond to verification prompts, and monitor payout status messages."
    }
]

print("Number of documents:", len(documents))
documents[:2]

Number of documents: 24

[{'doc_id': 'POL001',
  'category': 'policy',
  'title': 'Listing Suppression for Missing Mandatory Attributes',
  'content': 'Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation.'},
 {'doc_id': 'POL002',
  'category': 'policy',
  'title': 'Image Compliance Requirements',
  'content': 'Product listings may be restricted or hidden if primary images do not meet marketplace quality guidelines. Common violations include watermarks, text overlays, blurred images, incorrect background color, and non-product promotional graphics. Sellers should replace non-compliant images and wait for reprocessing.'}]

In [8]:
kb_df = pd.DataFrame(documents)
print("Knowledge base shape:", kb_df.shape)
kb_df.head(10)

Knowledge base shape: (24, 4)

,doc_id,category,title,content
0,POL001,policy,Listing Suppression for Missing Mandatory Attr...,Listings may be suppressed when required attri...
1,POL002,policy,Image Compliance Requirements,Product listings may be restricted or hidden i...
2,POL003,policy,Restricted Product Review Process,Some products require compliance review before...
3,POL004,policy,Title and Description Quality Rules,Listings may lose visibility if titles and des...
4,POL005,policy,Duplicate Listing Policy,Multiple listings for the same product may cre...
5,POL006,policy,Hazmat and Safety Documentation Requirements,Products classified as hazardous or safety-sen...
6,OPS001,operations,Inventory Mismatch Troubleshooting,Inventory mismatch occurs when available stock...
7,OPS002,operations,Late Shipment Prevention,Late shipment risk increases when order handli...
8,OPS003,operations,Stranded Inventory Resolution,Inventory becomes stranded when units in the f...
9,OPS004,operations,Inbound Shipment Receiving Delays,Inbound receiving delays may happen when fulfi...

In [9]:
print("category distribution:")
print(kb_df["category"].value_counts())

category distribution:
category
policy            6
operations        6
account_health    6
payments          6
Name: count, dtype: int64

In [10]:
kb_df.to_csv("data/seller_ops_knowledge_base.csv", index=False)
print("Saved Knowledge base to data/seller_ops_knowledge_base.csv")

Saved Knowledge base to data/seller_ops_knowledge_base.csv

In [11]:
kb_df.sample(5, random_state=42)

,doc_id,category,title,content
8,OPS003,operations,Stranded Inventory Resolution,Inventory becomes stranded when units in the f...
16,ACC005,account_health,Customer Complaint Escalation Risk,"Repeated complaints related to item condition,..."
0,POL001,policy,Listing Suppression for Missing Mandatory Attr...,Listings may be suppressed when required attri...
18,PAY001,payments,Reimbursement Rejection Due to Missing Documen...,Reimbursement claims may be rejected when invo...
11,OPS006,operations,Carrier Pickup Failure Response,Carrier pickup failures can lead to missed dis...

In [14]:
import os
os.makedirs("src", exist_ok=True)
print("src folder created")

src folder created

In [15]:
%%writefile src/kb_loader.py
import pandas as pd
def load_knowledge_base(filepath="data/seller_ops_knowledge_base.csv"):
  return pd.read_csv(filepath)
def get_documents_as_dicts(df):
  return df.to_dict(orient="records")

Writing src/kb_loader.py

In [2]:
!pip install sentence-transformers scikit-learn -q

In [4]:
import os
os.makedirs("src", exist_ok=True)
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
print("Folders verified")

Folders verified

In [5]:
%%writefile src/retriever.py
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

class SellerOpsRetriever:
    def __init__(self, model_name="all-MiniLM-L6-v2"):
        self.model_name = model_name
        self.model = SentenceTransformer(model_name)
        self.kb_df = None
        self.doc_texts = None
        self.doc_embeddings = None

    def prepare_documents(self, kb_df: pd.DataFrame):
        self.kb_df = kb_df.copy()

        self.doc_texts = (
            "Category: " + self.kb_df["category"].astype(str) +
            " | Title: " + self.kb_df["title"].astype(str) +
            " | Content: " + self.kb_df["content"].astype(str)
        ).tolist()

        self.doc_embeddings = self.model.encode(
            self.doc_texts,
            convert_to_numpy=True,
            show_progress_bar=False
        )

    def retrieve(self, query: str, top_k: int = 3):
        if self.kb_df is None or self.doc_embeddings is None:
            raise ValueError("Retriever is not prepared. Call prepare_documents(kb_df) first.")

        query_embedding = self.model.encode([query], convert_to_numpy=True, show_progress_bar=False)
        similarities = cosine_similarity(query_embedding, self.doc_embeddings)[0]

        top_indices = np.argsort(similarities)[::-1][:top_k]

        results = self.kb_df.iloc[top_indices].copy()
        results["similarity_score"] = similarities[top_indices]

        return results[[
            "doc_id", "category", "title", "content", "similarity_score"
        ]].reset_index(drop=True)

    def retrieve_with_texts(self, query: str, top_k: int = 3):
        results = self.retrieve(query, top_k=top_k)
        return results.to_dict(orient="records")

Writing src/retriever.py

In [15]:
import os
print("Current directory files:", os.listdir())
print("src folder contents:", os.listdir("src"))

Current directory files: ['.config', 'src', 'data', 'results', 'sample_data']
src folder contents: ['__pycache__', 'retriever.py']

In [16]:
%%writefile src/kb_loader.py
import pandas as pd
def load_knowledge_base(filepath="data/seller_ops_knowledge_base.csv"):
  return pd.read_csv(filepath)
def get_documents_as_dicts(df):
  return df.to_dict(orient="records")

Writing src/kb_loader.py

In [17]:
with open("src/__init__.py", "w") as f:
  f.write("")

In [19]:
import sys
sys.path.append("/content")

from src.kb_loader import load_knowledge_base, get_documents_as_dicts
from src.retriever import SellerOpsRetriever

print("Imports working now.")

Imports working now.

In [20]:
import os
print(os.listdir("src"))

['__init__.py', '__pycache__', 'kb_loader.py', 'retriever.py']

In [25]:
import os
print(os.listdir("data"))

[]

In [26]:
documents = [
    {
        "doc_id": "POL001",
        "category": "policy",
        "title": "Listing Suppression for Missing Mandatory Attributes",
        "content": "Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation."
    },
    {
        "doc_id": "OPS001",
        "category": "operations",
        "title": "Inventory Mismatch Troubleshooting",
        "content": "Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantities. Sellers should reconcile inventory reports and verify inbound receipts."
    },
    {
        "doc_id": "ACC001",
        "category": "account_health",
        "title": "Late Shipment Rate Threshold",
        "content": "Late shipment rate measures the percentage of seller-fulfilled orders confirmed after the expected ship date. Sellers should improve order processing."
    },
    {
        "doc_id": "PAY001",
        "category": "payments",
        "title": "Reimbursement Rejection Due to Missing Documentation",
        "content": "Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent."
    }
]

import pandas as pd

kb_df = pd.DataFrame(documents)
kb_df.to_csv("data/seller_ops_knowledge_base.csv", index=False)

print("Knowledge base recreated ✅")

Knowledge base recreated ✅

In [27]:
import os
print(os.listdir("data"))

['seller_ops_knowledge_base.csv']

In [28]:
kb_df = load_knowledge_base("data/seller_ops_knowledge_base.csv")
print(kb_df.shape)
kb_df.head()

(4, 4)

   doc_id  ...                                            content
0  POL001  ...  Listings may be suppressed when required attri...
1  OPS001  ...  Inventory mismatch occurs when available stock...
2  ACC001  ...  Late shipment rate measures the percentage of ...
3  PAY001  ...  Reimbursement claims may be rejected when supp...

[4 rows x 4 columns]

In [29]:
%%writefile src/router.py
import re
import pandas as pd


class QueryRouter:
    def __init__(self):
        self.category_keywords = {
            "policy": [
                "listing", "suppressed", "policy", "image", "title", "description",
                "restricted", "compliance", "hazmat", "duplicate", "attribute"
            ],
            "operations": [
                "inventory", "shipment", "fulfillment", "delay", "carrier", "pickup",
                "warehouse", "processing", "stranded", "cancellation", "dispatch"
            ],
            "account_health": [
                "account health", "warning", "appeal", "late shipment rate",
                "valid tracking rate", "order defect", "performance", "notification",
                "complaint", "metric"
            ],
            "payments": [
                "payment", "payout", "reimbursement", "claim", "invoice",
                "chargeback", "bank", "verification", "documentation", "hold"
            ]
        }

    def _normalize_text(self, text: str) -> str:
        text = text.lower().strip()
        text = re.sub(r"\s+", " ", text)
        return text

    def keyword_route(self, query: str):
        query_norm = self._normalize_text(query)
        scores = {category: 0 for category in self.category_keywords}

        for category, keywords in self.category_keywords.items():
            for keyword in keywords:
                if keyword in query_norm:
                    scores[category] += 1

        best_category = max(scores, key=scores.get)
        best_score = scores[best_category]

        if best_score == 0:
            confidence = 0.25
            reason = "No strong keyword match found; routing will rely more on retrieval context."
        else:
            confidence = min(0.40 + (0.10 * best_score), 0.90)
            reason = f"Matched {best_score} keyword(s) related to {best_category}."

        return {
            "predicted_category": best_category,
            "scores": scores,
            "confidence": round(confidence, 2),
            "reason": reason
        }

    def retrieval_route(self, retrieved_docs: pd.DataFrame):
        if retrieved_docs is None or len(retrieved_docs) == 0:
            return {
                "predicted_category": "operations",
                "category_scores": {},
                "confidence": 0.20,
                "reason": "No retrieved documents available; default fallback route used."
            }

        category_scores = (
            retrieved_docs.groupby("category")["similarity_score"]
            .sum()
            .sort_values(ascending=False)
            .to_dict()
        )

        best_category = max(category_scores, key=category_scores.get)
        total_score = sum(category_scores.values())
        best_score = category_scores[best_category]

        confidence = best_score / total_score if total_score > 0 else 0.25

        return {
            "predicted_category": best_category,
            "category_scores": category_scores,
            "confidence": round(float(confidence), 2),
            "reason": f"Top retrieved evidence is strongest for {best_category}."
        }

    def hybrid_route(self, query: str, retrieved_docs: pd.DataFrame):
        keyword_result = self.keyword_route(query)
        retrieval_result = self.retrieval_route(retrieved_docs)

        keyword_category = keyword_result["predicted_category"]
        retrieval_category = retrieval_result["predicted_category"]

        if keyword_category == retrieval_category:
            final_category = keyword_category
            confidence = min(
                0.55 * keyword_result["confidence"] + 0.45 * retrieval_result["confidence"] + 0.10,
                0.95
            )
            reason = (
                f"Keyword routing and retrieval routing agree on {final_category}. "
                f"{keyword_result['reason']} {retrieval_result['reason']}"
            )
        else:
            if retrieval_result["confidence"] >= keyword_result["confidence"]:
                final_category = retrieval_category
                confidence = min(0.55 * retrieval_result["confidence"] + 0.45 * keyword_result["confidence"], 0.90)
                reason = (
                    f"Keyword routing suggested {keyword_category}, but retrieval evidence was stronger for "
                    f"{retrieval_category}. Final route selected from retrieval evidence."
                )
            else:
                final_category = keyword_category
                confidence = min(0.55 * keyword_result["confidence"] + 0.45 * retrieval_result["confidence"], 0.90)
                reason = (
                    f"Retrieval suggested {retrieval_category}, but keyword evidence was stronger for "
                    f"{keyword_category}. Final route selected from query intent."
                )

        return {
            "predicted_category": final_category,
            "confidence": round(confidence, 2),
            "keyword_route": keyword_result,
            "retrieval_route": retrieval_result,
            "reason": reason
        }

Writing src/router.py

In [31]:
from src.router import QueryRouter
print("Router imported successfully.")

Router imported successfully.

In [33]:
router = QueryRouter()
query_a = "Why was my listing suppressed due to missing attributes?"
keyword_result_a = router.keyword_route(query_a)
keyword_result_a

{'predicted_category': 'policy',
 'scores': {'policy': 3, 'operations': 0, 'account_health': 0, 'payments': 0},
 'confidence': 0.7,
 'reason': 'Matched 3 keyword(s) related to policy.'}

In [35]:
retriever = SellerOpsRetriever()
retriever.prepare_documents(kb_df)
retrieved_a = retriever.retrieve(query_a, top_k=3)
retrieved_a

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

   doc_id  ... similarity_score
0  POL001  ...         0.626515
1  PAY001  ...         0.275400
2  OPS001  ...         0.244531

[3 rows x 5 columns]

In [38]:
hybrid_route_a = router.hybrid_route(query_a, retrieved_a)
hybrid_route_a

{'predicted_category': 'policy',
 'confidence': 0.73,
 'keyword_route': {'predicted_category': 'policy',
  'scores': {'policy': 3, 'operations': 0, 'account_health': 0, 'payments': 0},
  'confidence': 0.7,
  'reason': 'Matched 3 keyword(s) related to policy.'},
 'retrieval_route': {'predicted_category': 'policy',
  'category_scores': {'policy': 0.6265154480934143,
   'payments': 0.2754000127315521,
   'operations': 0.24453140795230865},
  'confidence': 0.55,
  'reason': 'Top retrieved evidence is strongest for policy.'},
 'reason': 'Keyword routing and retrieval routing agree on policy. Matched 3 keyword(s) related to policy. Top retrieved evidence is strongest for policy.'}

In [39]:
router_test_queries = [
    "My reimbursement request was denied because my invoice was incomplete",
    "How do I fix a valid tracking rate warning?",
    "My payout is delayed due to bank verification",
    "How can I reduce late shipment risk for seller fulfilled orders?",
    "My primary product image is non-compliant",
    "Why is my inventory mismatched with warehouse stock?"
]

for q in router_test_queries:
    retrieved = retriever.retrieve(q, top_k=3)
    route = router.hybrid_route(q, retrieved)

    print("\n" + "=" * 100)
    print("Query:", q)
    print("Predicted Category:", route["predicted_category"])
    print("Confidence:", route["confidence"])
    print("Reason:", route["reason"])

====================================================================================================
Query: My reimbursement request was denied because my invoice was incomplete
Predicted Category: payments
Confidence: 0.7
Reason: Keyword routing and retrieval routing agree on payments. Matched 2 keyword(s) related to payments. Top retrieved evidence is strongest for payments.

====================================================================================================
Query: How do I fix a valid tracking rate warning?
Predicted Category: account_health
Confidence: 0.63
Reason: Keyword routing and retrieval routing agree on account_health. Matched 2 keyword(s) related to account_health. Top retrieved evidence is strongest for account_health.

====================================================================================================
Query: My payout is delayed due to bank verification
Predicted Category: payments
Confidence: 0.69
Reason: Keyword routing and retrieval routing agree on payments. Matched 3 keyword(s) related to payments. Top retrieved evidence is strongest for payments.

====================================================================================================
Query: How can I reduce late shipment risk for seller fulfilled orders?
Predicted Category: operations
Confidence: 0.5
Reason: Retrieval suggested account_health, but keyword evidence was stronger for operations. Final route selected from query intent.

====================================================================================================
Query: My primary product image is non-compliant
Predicted Category: policy
Confidence: 0.55
Reason: Keyword routing and retrieval routing agree on policy. Matched 1 keyword(s) related to policy. Top retrieved evidence is strongest for policy.

====================================================================================================
Query: Why is my inventory mismatched with warehouse stock?
Predicted Category: operations
Confidence: 0.67
Reason: Keyword routing and retrieval routing agree on operations. Matched 2 keyword(s) related to operations. Top retrieved evidence is strongest for operations.

In [40]:
def show_router_decision(query, route_result):
    print(f"Query: {query}")
    print("=" * 80)
    print("Final Predicted Category:", route_result["predicted_category"])
    print("Final Confidence:", route_result["confidence"])
    print("Reason:", route_result["reason"])
    print("\nKeyword Route:")
    print(route_result["keyword_route"])
    print("\nRetrieval Route:")
    print(route_result["retrieval_route"])

In [41]:
show_router_decision(query_a, hybrid_route_a)

Query: Why was my listing suppressed due to missing attributes?
================================================================================
Final Predicted Category: policy
Final Confidence: 0.73
Reason: Keyword routing and retrieval routing agree on policy. Matched 3 keyword(s) related to policy. Top retrieved evidence is strongest for policy.

Keyword Route:
{'predicted_category': 'policy', 'scores': {'policy': 3, 'operations': 0, 'account_health': 0, 'payments': 0}, 'confidence': 0.7, 'reason': 'Matched 3 keyword(s) related to policy.'}

Retrieval Route:
{'predicted_category': 'policy', 'category_scores': {'policy': 0.6265154480934143, 'payments': 0.2754000127315521, 'operations': 0.24453140795230865}, 'confidence': 0.55, 'reason': 'Top retrieved evidence is strongest for policy.'}

In [42]:
routing_eval_data = [
    {
        "query": "My listing was suppressed because required product details are missing",
        "expected_category": "policy"
    },
    {
        "query": "My product image was rejected due to quality guidelines",
        "expected_category": "policy"
    },
    {
        "query": "I need to resolve inventory mismatch between actual stock and system stock",
        "expected_category": "operations"
    },
    {
        "query": "How do I reduce late shipment risk for seller fulfilled orders?",
        "expected_category": "operations"
    },
    {
        "query": "I received an order defect rate warning and want to submit an appeal",
        "expected_category": "account_health"
    },
    {
        "query": "How do I fix a valid tracking rate issue?",
        "expected_category": "account_health"
    },
    {
        "query": "My reimbursement claim was rejected due to missing documents",
        "expected_category": "payments"
    },
    {
        "query": "Why is my payout delayed because of banking verification?",
        "expected_category": "payments"
    }
]

routing_eval_df = pd.DataFrame(routing_eval_data)
routing_eval_df

                                               query expected_category
0  My listing was suppressed because required pro...            policy
1  My product image was rejected due to quality g...            policy
2  I need to resolve inventory mismatch between a...        operations
3  How do I reduce late shipment risk for seller ...        operations
4  I received an order defect rate warning and wa...    account_health
5          How do I fix a valid tracking rate issue?    account_health
6  My reimbursement claim was rejected due to mis...          payments
7  Why is my payout delayed because of banking ve...          payments

In [43]:
routing_eval_data = [
    {
        "query": "My listing was suppressed because required product details are missing",
        "expected_category": "policy"
    },
    {
        "query": "My product image was rejected due to quality guidelines",
        "expected_category": "policy"
    },
    {
        "query": "I need to resolve inventory mismatch between actual stock and system stock",
        "expected_category": "operations"
    },
    {
        "query": "How do I reduce late shipment risk for seller fulfilled orders?",
        "expected_category": "operations"
    },
    {
        "query": "I received an order defect rate warning and want to submit an appeal",
        "expected_category": "account_health"
    },
    {
        "query": "How do I fix a valid tracking rate issue?",
        "expected_category": "account_health"
    },
    {
        "query": "My reimbursement claim was rejected due to missing documents",
        "expected_category": "payments"
    },
    {
        "query": "Why is my payout delayed because of banking verification?",
        "expected_category": "payments"
    }
]

routing_eval_df = pd.DataFrame(routing_eval_data)
routing_eval_df

                                               query expected_category
0  My listing was suppressed because required pro...            policy
1  My product image was rejected due to quality g...            policy
2  I need to resolve inventory mismatch between a...        operations
3  How do I reduce late shipment risk for seller ...        operations
4  I received an order defect rate warning and wa...    account_health
5          How do I fix a valid tracking rate issue?    account_health
6  My reimbursement claim was rejected due to mis...          payments
7  Why is my payout delayed because of banking ve...          payments

In [45]:
results = []
for index, row in routing_eval_df.iterrows():
    query = row["query"]
    expected_category = row["expected_category"]

    # Retrieve documents for the query
    retrieved_docs = retriever.retrieve(query, top_k=3)

    # Route the query using the hybrid approach
    route_result = router.hybrid_route(query, retrieved_docs)

    predicted_category = route_result["predicted_category"]
    confidence = route_result["confidence"]

    results.append({
        "query": query,
        "expected_category": expected_category,
        "predicted_category": predicted_category,
        "confidence": confidence,
        "correct": (predicted_category == expected_category)
    })

routing_eval_results_df = pd.DataFrame(results)

routing_accuracy = routing_eval_results_df["correct"].mean()

print("Router Evaluation Summary")
print("=" * 60)
print(f"Hybrid Router Accuracy: {routing_accuracy:.4f}")
print("\nPredicted category distribution:")
print(routing_eval_results_df["predicted_category"].value_counts())

Router Evaluation Summary
============================================================
Hybrid Router Accuracy: 1.0000

Predicted category distribution:
predicted_category
policy            2
operations        2
account_health    2
payments          2
Name: count, dtype: int64

In [46]:
routing_eval_results_df[routing_eval_results_df["correct"]==0]

Empty DataFrame
Columns: [query, expected_category, predicted_category, confidence, correct]
Index: []

In [47]:
comparison_rows = []

for _, row in routing_eval_df.iterrows():
    query = row["query"]
    expected_category = row["expected_category"]

    keyword_route = router.keyword_route(query)
    retrieved = retriever.retrieve(query, top_k=3)
    hybrid_route = router.hybrid_route(query, retrieved)

    comparison_rows.append({
        "query": query,
        "expected_category": expected_category,
        "keyword_pred": keyword_route["predicted_category"],
        "keyword_correct": int(keyword_route["predicted_category"] == expected_category),
        "hybrid_pred": hybrid_route["predicted_category"],
        "hybrid_correct": int(hybrid_route["predicted_category"] == expected_category)
    })

routing_compare_df = pd.DataFrame(comparison_rows)
routing_compare_df

                                               query  ... hybrid_correct
0  My listing was suppressed because required pro...  ...              1
1  My product image was rejected due to quality g...  ...              1
2  I need to resolve inventory mismatch between a...  ...              1
3  How do I reduce late shipment risk for seller ...  ...              1
4  I received an order defect rate warning and wa...  ...              1
5          How do I fix a valid tracking rate issue?  ...              1
6  My reimbursement claim was rejected due to mis...  ...              1
7  Why is my payout delayed because of banking ve...  ...              1

[8 rows x 6 columns]

In [48]:
keyword_acc = routing_compare_df["keyword_correct"].mean()
hybrid_acc = routing_compare_df["hybrid_correct"].mean()

print("Routing Accuracy Comparison")
print("=" * 60)
print(f"Keyword-only Router Accuracy: {keyword_acc:.4f}")
print(f"Hybrid Router Accuracy      : {hybrid_acc:.4f}")

Routing Accuracy Comparison
============================================================
Keyword-only Router Accuracy: 1.0000
Hybrid Router Accuracy      : 1.0000

In [49]:
routing_eval_results_df.to_csv("results/routing_eval_results.csv", index=False)
routing_compare_df.to_csv("results/routing_compare_results.csv", index=False)

print("Saved:")
print("- results/routing_eval_results.csv")
print("- results/routing_compare_results.csv")

Saved:
- results/routing_eval_results.csv
- results/routing_compare_results.csv

In [50]:
realistic_queries = [
    "My listing is inactive because some compliance details are missing.",
    "I got a performance notification related to late shipment rate.",
    "Why is my reimbursement denied when I uploaded an invoice?",
    "My payout is on hold and I think verification is pending.",
    "Warehouse stock does not match what the system shows.",
    "My title and description may be causing search suppression."
]

batch_routes = []

for q in realistic_queries:
    retrieved = retriever.retrieve(q, top_k=3)
    route = router.hybrid_route(q, retrieved)

    batch_routes.append({
        "query": q,
        "predicted_category": route["predicted_category"],
        "confidence": route["confidence"],
        "reason": route["reason"]
    })

batch_routes_df = pd.DataFrame(batch_routes)
batch_routes_df

                                               query  ...                                             reason
0  My listing is inactive because some compliance...  ...  Keyword routing and retrieval routing agree on...
1  I got a performance notification related to la...  ...  Keyword routing and retrieval routing agree on...
2  Why is my reimbursement denied when I uploaded...  ...  Keyword routing and retrieval routing agree on...
3  My payout is on hold and I think verification ...  ...  Keyword routing and retrieval routing agree on...
4  Warehouse stock does not match what the system...  ...  Keyword routing and retrieval routing agree on...
5  My title and description may be causing search...  ...  Keyword routing and retrieval routing agree on...

[6 rows x 4 columns]

In [51]:
print("Project 2 — Step 3 Completed Successfully")
print("=" * 60)
print("Built:")
print("- Keyword-based router")
print("- Retrieval-informed router")
print("- Hybrid router")
print("- Router confidence scoring")
print("- Router evaluation pipeline")
print("\nSaved outputs:")
print("- results/routing_eval_results.csv")
print("- results/routing_compare_results.csv")

Project 2 — Step 3 Completed Successfully
============================================================
Built:
- Keyword-based router
- Retrieval-informed router
- Hybrid router
- Router confidence scoring
- Router evaluation pipeline

Saved outputs:
- results/routing_eval_results.csv
- results/routing_compare_results.csv

In [52]:
%%writefile src/agents.py
from typing import List, Dict


class BaseAgent:
    def __init__(self, name):
        self.name = name

    def format_response(self, query, retrieved_docs):
        context = " ".join([doc["content"] for doc in retrieved_docs])

        return {
            "agent": self.name,
            "query": query,
            "context_used": context[:500],
        }


class PolicyAgent(BaseAgent):
    def __init__(self):
        super().__init__("PolicyAgent")

    def handle(self, query: str, retrieved_docs: List[Dict]):
        base = self.format_response(query, retrieved_docs)

        findings = [doc["title"] for doc in retrieved_docs]

        actions = [
            "Review product listing details",
            "Update missing attributes",
            "Ensure compliance with listing policies"
        ]

        answer = f"Your issue appears related to listing policy compliance. {retrieved_docs[0]['content']}"

        return {
            **base,
            "category": "policy",
            "answer": answer,
            "findings": findings,
            "actions": actions,
            "confidence": 0.82
        }


class OperationsAgent(BaseAgent):
    def __init__(self):
        super().__init__("OperationsAgent")

    def handle(self, query: str, retrieved_docs: List[Dict]):
        base = self.format_response(query, retrieved_docs)

        findings = [doc["title"] for doc in retrieved_docs]

        actions = [
            "Check inventory consistency",
            "Verify shipment handling times",
            "Monitor carrier performance"
        ]

        answer = f"This appears to be an operational issue. {retrieved_docs[0]['content']}"

        return {
            **base,
            "category": "operations",
            "answer": answer,
            "findings": findings,
            "actions": actions,
            "confidence": 0.85
        }


class AccountHealthAgent(BaseAgent):
    def __init__(self):
        super().__init__("AccountHealthAgent")

    def handle(self, query: str, retrieved_docs: List[Dict]):
        base = self.format_response(query, retrieved_docs)

        findings = [doc["title"] for doc in retrieved_docs]

        actions = [
            "Review account performance metrics",
            "Address root cause of warning",
            "Submit appeal with corrective actions"
        ]

        answer = f"This relates to account health performance. {retrieved_docs[0]['content']}"

        return {
            **base,
            "category": "account_health",
            "answer": answer,
            "findings": findings,
            "actions": actions,
            "confidence": 0.83
        }


class PaymentsAgent(BaseAgent):
    def __init__(self):
        super().__init__("PaymentsAgent")

    def handle(self, query: str, retrieved_docs: List[Dict]):
        base = self.format_response(query, retrieved_docs)

        findings = [doc["title"] for doc in retrieved_docs]

        actions = [
            "Check documentation completeness",
            "Verify claim eligibility",
            "Re-submit with proper evidence"
        ]

        answer = f"This issue relates to payments or reimbursements. {retrieved_docs[0]['content']}"

        return {
            **base,
            "category": "payments",
            "answer": answer,
            "findings": findings,
            "actions": actions,
            "confidence": 0.84
        }

Writing src/agents.py

In [53]:
from src.agents import (
    PolicyAgent,
    OperationsAgent,
    AccountHealthAgent,
    PaymentsAgent
)
print("Agents Imported Successfully.")

Agents Imported Successfully.

In [54]:
policy_agent = PolicyAgent()
ops_agent = OperationsAgent()
account_agent = AccountHealthAgent()
payments_agent = PaymentsAgent()

print("All agents initialized.")

All agents initialized.

In [55]:
agent_map = {
    "policy": policy_agent,
    "operations": ops_agent,
    "account_health": account_agent,
    "payments": payments_agent
}

In [56]:
query = "My listing is suppressed due to missing attributes"

retrieved_docs = retriever.retrieve_with_texts(query, top_k=3)
route = router.hybrid_route(query, pd.DataFrame(retrieved_docs))

selected_agent = agent_map[route["predicted_category"]]

response = selected_agent.handle(query, retrieved_docs)

response

{'agent': 'PolicyAgent',
 'query': 'My listing is suppressed due to missing attributes',
 'context_used': 'Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent. Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantitie',
 'category': 'policy',
 'answer': 'Your issue appears related to listing policy compliance. Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation.',
 'findings': ['Listing Suppression for Missing Mandatory Attributes',
  'Reimbursement Rejection Due to Missing Documentation',
  'Inventory Mismatch Troubleshooting'],
 'actions': ['Review product listing details',
  'Update missing attributes',
  'Ensure compliance with listing policies'],
 'confidence': 0.82}

In [57]:
def show_agent_response(response):
    print("=" * 80)
    print("Agent:", response["agent"])
    print("Category:", response["category"])
    print("\nAnswer:")
    print(response["answer"])

    print("\nFindings:")
    for f in response["findings"]:
        print("-", f)

    print("\nActions:")
    for a in response["actions"]:
        print("-", a)

    print("\nConfidence:", response["confidence"])

In [58]:
show_agent_response(response)

================================================================================
Agent: PolicyAgent
Category: policy

Answer:
Your issue appears related to listing policy compliance. Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation.

Findings:
- Listing Suppression for Missing Mandatory Attributes
- Reimbursement Rejection Due to Missing Documentation
- Inventory Mismatch Troubleshooting

Actions:
- Review product listing details
- Update missing attributes
- Ensure compliance with listing policies

Confidence: 0.82

In [59]:
test_queries = [
    "My reimbursement request was rejected",
    "How do I fix late shipment rate warning?",
    "Inventory does not match warehouse stock",
    "My payout is delayed due to verification"
]

for q in test_queries:
    print("\n" + "#" * 100)

    retrieved = retriever.retrieve_with_texts(q, top_k=3)
    route = router.hybrid_route(q, pd.DataFrame(retrieved))
    agent = agent_map[route["predicted_category"]]

    result = agent.handle(q, retrieved)

    print("Query:", q)
    show_agent_response(result)

####################################################################################################
Query: My reimbursement request was rejected
================================================================================
Agent: PaymentsAgent
Category: payments

Answer:
This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.

Findings:
- Reimbursement Rejection Due to Missing Documentation
- Inventory Mismatch Troubleshooting
- Late Shipment Rate Threshold

Actions:
- Check documentation completeness
- Verify claim eligibility
- Re-submit with proper evidence

Confidence: 0.84

####################################################################################################
Query: How do I fix late shipment rate warning?
================================================================================
Agent: AccountHealthAgent
Category: account_health

Answer:
This relates to account health performance. Late shipment rate measures the percentage of seller-fulfilled orders confirmed after the expected ship date. Sellers should improve order processing.

Findings:
- Late Shipment Rate Threshold
- Inventory Mismatch Troubleshooting
- Listing Suppression for Missing Mandatory Attributes

Actions:
- Review account performance metrics
- Address root cause of warning
- Submit appeal with corrective actions

Confidence: 0.83

####################################################################################################
Query: Inventory does not match warehouse stock
================================================================================
Agent: OperationsAgent
Category: operations

Answer:
This appears to be an operational issue. Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantities. Sellers should reconcile inventory reports and verify inbound receipts.

Findings:
- Inventory Mismatch Troubleshooting
- Listing Suppression for Missing Mandatory Attributes
- Late Shipment Rate Threshold

Actions:
- Check inventory consistency
- Verify shipment handling times
- Monitor carrier performance

Confidence: 0.85

####################################################################################################
Query: My payout is delayed due to verification
================================================================================
Agent: PaymentsAgent
Category: payments

Answer:
This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.

Findings:
- Reimbursement Rejection Due to Missing Documentation
- Inventory Mismatch Troubleshooting
- Late Shipment Rate Threshold

Actions:
- Check documentation completeness
- Verify claim eligibility
- Re-submit with proper evidence

Confidence: 0.84

In [60]:
agent_outputs = []

for q in test_queries:
    retrieved = retriever.retrieve_with_texts(q, top_k=3)
    route = router.hybrid_route(q, pd.DataFrame(retrieved))
    agent = agent_map[route["predicted_category"]]

    result = agent.handle(q, retrieved)

    agent_outputs.append({
        "query": q,
        "agent": result["agent"],
        "category": result["category"],
        "answer": result["answer"],
        "confidence": result["confidence"]
    })

agent_outputs_df = pd.DataFrame(agent_outputs)
agent_outputs_df.to_csv("results/agent_outputs.csv", index=False)

agent_outputs_df

                                      query  ... confidence
0     My reimbursement request was rejected  ...       0.84
1  How do I fix late shipment rate warning?  ...       0.83
2  Inventory does not match warehouse stock  ...       0.85
3  My payout is delayed due to verification  ...       0.84

[4 rows x 5 columns]

In [61]:
print("Project 2 — Step 4 Completed Successfully")
print("=" * 60)

print("Built:")
print("- 4 Specialist Agents")
print("- Structured outputs")
print("- Agent routing integration")
print("- Action recommendations")
print("- Evidence-based responses")

print("\nSaved:")
print("- results/agent_outputs.csv")

Project 2 — Step 4 Completed Successfully
============================================================
Built:
- 4 Specialist Agents
- Structured outputs
- Agent routing integration
- Action recommendations
- Evidence-based responses

Saved:
- results/agent_outputs.csv

In [62]:
%%writefile src/orchestrator.py
import pandas as pd


class ManagerAgent:
    def __init__(self):
        self.name = "ManagerAgent"

    def combine(self, query, route_result, agent_response):
        final_risk = "Low"

        if route_result["confidence"] > 0.75 and agent_response["confidence"] > 0.8:
            final_risk = "High"
        elif route_result["confidence"] > 0.5:
            final_risk = "Medium"

        return {
            "query": query,
            "selected_agent": agent_response["agent"],
            "category": agent_response["category"],
            "final_answer": agent_response["answer"],
            "root_cause": agent_response["findings"][0],
            "actions": agent_response["actions"],
            "confidence": round((route_result["confidence"] + agent_response["confidence"]) / 2, 2),
            "risk_level": final_risk,
            "reasoning": route_result["reason"]
        }


class AgenticRAGOrchestrator:
    def __init__(self, retriever, router, agent_map):
        self.retriever = retriever
        self.router = router
        self.agent_map = agent_map
        self.manager = ManagerAgent()

    def run(self, query: str, top_k: int = 3):
        # Step 1: Retrieve
        retrieved_docs = self.retriever.retrieve_with_texts(query, top_k=top_k)

        # Step 2: Route
        route_result = self.router.hybrid_route(query, pd.DataFrame(retrieved_docs))

        # Step 3: Select agent
        agent = self.agent_map[route_result["predicted_category"]]

        # Step 4: Agent response
        agent_response = agent.handle(query, retrieved_docs)

        # Step 5: Manager combines
        final_output = self.manager.combine(query, route_result, agent_response)

        return {
            "retrieved_docs": retrieved_docs,
            "route": route_result,
            "agent_response": agent_response,
            "final_output": final_output
        }

Writing src/orchestrator.py

In [63]:
from src.orchestrator import AgenticRAGOrchestrator

print("Orchestrator imported.")

Orchestrator imported.

In [64]:
orchestrator = AgenticRAGOrchestrator(
    retriever=retriever,
    router=router,
    agent_map=agent_map
)

print("Orchestrator ready.")

Orchestrator ready.

In [65]:
query = "My reimbursement request was rejected due to missing invoice"

result = orchestrator.run(query)

result["final_output"]

{'query': 'My reimbursement request was rejected due to missing invoice',
 'selected_agent': 'PaymentsAgent',
 'category': 'payments',
 'final_answer': 'This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.',
 'root_cause': 'Reimbursement Rejection Due to Missing Documentation',
 'actions': ['Check documentation completeness',
  'Verify claim eligibility',
  'Re-submit with proper evidence'],
 'confidence': 0.76,
 'risk_level': 'Medium',
 'reasoning': 'Keyword routing and retrieval routing agree on payments. Matched 2 keyword(s) related to payments. Top retrieved evidence is strongest for payments.'}

In [66]:
def show_final_output(result):
    print("=" * 80)
    print("QUERY:", result["final_output"]["query"])

    print("\nSelected Agent:", result["final_output"]["selected_agent"])
    print("Category:", result["final_output"]["category"])
    print("Risk Level:", result["final_output"]["risk_level"])

    print("\nFINAL ANSWER:")
    print(result["final_output"]["final_answer"])

    print("\nROOT CAUSE:")
    print(result["final_output"]["root_cause"])

    print("\nRECOMMENDED ACTIONS:")
    for action in result["final_output"]["actions"]:
        print("-", action)

    print("\nCONFIDENCE:", result["final_output"]["confidence"])

    print("\nREASONING:")
    print(result["final_output"]["reasoning"])

In [68]:
show_final_output(result)

================================================================================
QUERY: My reimbursement request was rejected due to missing invoice

Selected Agent: PaymentsAgent
Category: payments
Risk Level: Medium

FINAL ANSWER:
This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.

ROOT CAUSE:
Reimbursement Rejection Due to Missing Documentation

RECOMMENDED ACTIONS:
- Check documentation completeness
- Verify claim eligibility
- Re-submit with proper evidence

CONFIDENCE: 0.76

REASONING:
Keyword routing and retrieval routing agree on payments. Matched 2 keyword(s) related to payments. Top retrieved evidence is strongest for payments.

In [69]:
queries = [
    "Why was my listing suppressed?",
    "Inventory does not match warehouse stock",
    "I got a late shipment rate warning",
    "My payout is delayed due to bank verification",
    "My reimbursement claim was rejected"
]

all_outputs = []

for q in queries:
    result = orchestrator.run(q)
    show_final_output(result)

    all_outputs.append(result["final_output"])

================================================================================
QUERY: Why was my listing suppressed?

Selected Agent: PolicyAgent
Category: policy
Risk Level: Medium

FINAL ANSWER:
Your issue appears related to listing policy compliance. Listings may be suppressed when required attributes such as brand, product type, size, material, or compliance fields are missing. Sellers should review the inventory management page, identify missing attributes, update product data, and resubmit the listing for validation.

ROOT CAUSE:
Listing Suppression for Missing Mandatory Attributes

RECOMMENDED ACTIONS:
- Review product listing details
- Update missing attributes
- Ensure compliance with listing policies

CONFIDENCE: 0.74

REASONING:
Keyword routing and retrieval routing agree on policy. Matched 2 keyword(s) related to policy. Top retrieved evidence is strongest for policy.
================================================================================
QUERY: Inventory does not match warehouse stock

Selected Agent: OperationsAgent
Category: operations
Risk Level: Medium

FINAL ANSWER:
This appears to be an operational issue. Inventory mismatch occurs when available stock recorded in the catalog does not match physical or fulfillment network quantities. Sellers should reconcile inventory reports and verify inbound receipts.

ROOT CAUSE:
Inventory Mismatch Troubleshooting

RECOMMENDED ACTIONS:
- Check inventory consistency
- Verify shipment handling times
- Monitor carrier performance

CONFIDENCE: 0.76

REASONING:
Keyword routing and retrieval routing agree on operations. Matched 2 keyword(s) related to operations. Top retrieved evidence is strongest for operations.
================================================================================
QUERY: I got a late shipment rate warning

Selected Agent: AccountHealthAgent
Category: account_health
Risk Level: Medium

FINAL ANSWER:
This relates to account health performance. Late shipment rate measures the percentage of seller-fulfilled orders confirmed after the expected ship date. Sellers should improve order processing.

ROOT CAUSE:
Late Shipment Rate Threshold

RECOMMENDED ACTIONS:
- Review account performance metrics
- Address root cause of warning
- Submit appeal with corrective actions

CONFIDENCE: 0.74

REASONING:
Keyword routing and retrieval routing agree on account_health. Matched 2 keyword(s) related to account_health. Top retrieved evidence is strongest for account_health.
================================================================================
QUERY: My payout is delayed due to bank verification

Selected Agent: PaymentsAgent
Category: payments
Risk Level: Medium

FINAL ANSWER:
This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.

ROOT CAUSE:
Reimbursement Rejection Due to Missing Documentation

RECOMMENDED ACTIONS:
- Check documentation completeness
- Verify claim eligibility
- Re-submit with proper evidence

CONFIDENCE: 0.76

REASONING:
Keyword routing and retrieval routing agree on payments. Matched 3 keyword(s) related to payments. Top retrieved evidence is strongest for payments.
================================================================================
QUERY: My reimbursement claim was rejected

Selected Agent: PaymentsAgent
Category: payments
Risk Level: Medium

FINAL ANSWER:
This issue relates to payments or reimbursements. Reimbursement claims may be rejected when supporting documentation is incomplete or inconsistent.

ROOT CAUSE:
Reimbursement Rejection Due to Missing Documentation

RECOMMENDED ACTIONS:
- Check documentation completeness
- Verify claim eligibility
- Re-submit with proper evidence

CONFIDENCE: 0.79

REASONING:
Keyword routing and retrieval routing agree on payments. Matched 2 keyword(s) related to payments. Top retrieved evidence is strongest for payments.

In [70]:
final_df = pd.DataFrame(all_outputs)
final_df.to_csv("results/final_outputs.csv", index=False)

final_df

                                           query  ...                                          reasoning
0                 Why was my listing suppressed?  ...  Keyword routing and retrieval routing agree on...
1       Inventory does not match warehouse stock  ...  Keyword routing and retrieval routing agree on...
2             I got a late shipment rate warning  ...  Keyword routing and retrieval routing agree on...
3  My payout is delayed due to bank verification  ...  Keyword routing and retrieval routing agree on...
4            My reimbursement claim was rejected  ...  Keyword routing and retrieval routing agree on...

[5 rows x 9 columns]

In [71]:
comparison_rows = []

for q in queries:
    retrieved = retriever.retrieve(q, top_k=3)
    route = router.hybrid_route(q, retrieved)
    agent = agent_map[route["predicted_category"]]
    agent_result = agent.handle(q, retriever.retrieve_with_texts(q))

    comparison_rows.append({
        "query": q,
        "retrieved_category": retrieved.iloc[0]["category"],
        "routed_category": route["predicted_category"],
        "agent_used": agent_result["agent"]
    })

comparison_df = pd.DataFrame(comparison_rows)
comparison_df

                                           query  ...          agent_used
0                 Why was my listing suppressed?  ...         PolicyAgent
1       Inventory does not match warehouse stock  ...     OperationsAgent
2             I got a late shipment rate warning  ...  AccountHealthAgent
3  My payout is delayed due to bank verification  ...       PaymentsAgent
4            My reimbursement claim was rejected  ...       PaymentsAgent

[5 rows x 4 columns]

In [72]:
print("Project 2 — CORE SYSTEM COMPLETED")
print("=" * 60)

print("You built:")
print("- RAG retrieval system")
print("- Query router")
print("- Multi-agent system")
print("- Manager/orchestrator agent")
print("- End-to-end pipeline")

print("\nThis is now a FULL Agentic AI system.")

Project 2 — CORE SYSTEM COMPLETED
============================================================
You built:
- RAG retrieval system
- Query router
- Multi-agent system
- Manager/orchestrator agent
- End-to-end pipeline

This is now a FULL Agentic AI system.

In [73]:
%%writefile streamlit_app.py
import streamlit as st
import pandas as pd
import sys
import os

# Fix paths
sys.path.append("/content")

# Import modules
from src.kb_loader import load_knowledge_base
from src.retriever import SellerOpsRetriever
from src.router import QueryRouter
from src.agents import (
    PolicyAgent,
    OperationsAgent,
    AccountHealthAgent,
    PaymentsAgent
)
from src.orchestrator import AgenticRAGOrchestrator


# =========================
# Initialize system
# =========================
@st.cache_resource
def init_system():
    kb_df = load_knowledge_base("data/seller_ops_knowledge_base.csv")

    retriever = SellerOpsRetriever()
    retriever.prepare_documents(kb_df)

    router = QueryRouter()

    agent_map = {
        "policy": PolicyAgent(),
        "operations": OperationsAgent(),
        "account_health": AccountHealthAgent(),
        "payments": PaymentsAgent()
    }

    orchestrator = AgenticRAGOrchestrator(
        retriever=retriever,
        router=router,
        agent_map=agent_map
    )

    return orchestrator


orchestrator = init_system()

# =========================
# UI
# =========================
st.set_page_config(page_title="Agentic RAG Copilot", layout="wide")

st.title("Agentic RAG Copilot for Seller Operations")

st.markdown("""
This system uses:
- Retrieval (RAG)
- Multi-Agent Routing
- Specialist Agents
- Manager Orchestration

to resolve seller support queries.
""")

query = st.text_input("Enter your issue:", "")

if st.button("Resolve Issue"):

    if not query.strip():
        st.warning("Please enter a query.")
    else:
        result = orchestrator.run(query)

        final = result["final_output"]
        route = result["route"]
        retrieved = result["retrieved_docs"]

        st.subheader("Final Answer")
        st.write(final["final_answer"])

        st.subheader("Decision Details")
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Agent", final["selected_agent"])

        with col2:
            st.metric("Category", final["category"])

        with col3:
            st.metric("Confidence", final["confidence"])

        st.subheader("Risk Level")
        st.write(final["risk_level"])

        st.subheader("Root Cause")
        st.write(final["root_cause"])

        st.subheader("Recommended Actions")
        for action in final["actions"]:
            st.write("-", action)

        st.subheader("Routing Reasoning")
        st.write(route["reason"])

        st.subheader("Retrieved Evidence")
        for doc in retrieved:
            with st.expander(f"{doc['title']} (Score: {round(doc['similarity_score'], 3)})"):
                st.write(doc["content"])

Writing streamlit_app.py

In [74]:
!pip install streamlit -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 58.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 90.9 MB/s eta 0:00:00

In [89]:
!streamlit run streamlit_app &>/content/logs.txt &

In [90]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

In [91]:
!streamlit run streamlit_app.py >streamlit.log 2>1&1 &

/bin/bash: line 1: 1: command not found

In [92]:
!cat streamlit.log | tail -n 50

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://172.28.0.12:8502
  External URL: http://35.236.233.133:8502

In [93]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!nohup ./cloudflared tunnel --url http://localhost:8501 > cloudflared.log 2>&1 &

In [95]:
import time
time.sleep(8)

In [96]:
!cat cloudfared.log

cat: cloudfared.log: No such file or directory

In [97]:
import re

with open("cloudflared.log", "r") as f:
    log_text = f.read()

match = re.search(r"https://[-a-z0-9]+\.trycloudflare\.com", log_text)
if match:
    print("Streamlit App URL:", match.group(0))
else:
    print("Still no URL found.")

Streamlit App URL: https://jewellery-touched-fallen-loud.trycloudflare.com

In [98]:
!cat streamlit.log | tail -n 100

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://172.28.0.12:8502
  External URL: http://35.236.233.133:8502

In [99]:
!npm install -g localtunnel
!streanlit run streamlit_app.py > streamlit.log 2>&1 &
!lt --port 8501 > 1t.log 2>&1 &

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏
added 22 packages in 4s
⠏
⠏3 packages are looking for funding
⠏  run `npm fund` for details
⠏

In [100]:
!cat 1t.log

your url is: https://bright-oranges-thank.loca.lt

In [102]:
!curl ipv4.icanhazip.com

35.236.233.133